# ch-test-scope: full
FROM jcsda/docker-intel-oneapi-dev:beta
LABEL maintainer "Mark Miesch <miesch@ucar.edu>"

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
RUN apt-get update 

# Charliecloud does not modify the environment variables.  So, to set 
# environment variables we need to put them in an initialization script
RUN echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> /etc/bash.bashrc && \
    echo 'export PATH=/usr/local/mpich/bin:$PATH' >> /etc/bash.bashrc && \
    echo 'export NETCDF=/usr/local' >> /etc/bash.bashrc && \
    echo 'export PNETCDF=/usr/local' >> /etc/bash.bashrc && \
    echo 'export PIO=/usr/local' >> /etc/bash.bashrc && \
    echo 'export BOOST_ROOT=/usr/local' >> /etc/bash.bashrc && \
    echo 'export EIGEN3_INCLUDE_DIR=/usr/local' >> /etc/bash.bashrc && \
    echo 'export PYTHONPATH=/usr/local/lib:$PYTHONPATH' >> /etc/bash.bashrc && \
    echo 'export FC=mpiifort' >> /etc/bash.bashrc && \
    echo 'export CC=mpiicc' >> /etc/bash.bashrc && \
    echo 'export CXX=mpiicpc' >> /etc/bash.bashrc
